server:
  port: 8081
Spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/reactspringboot
    username: root
    password: Upen@1988
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    sql: debug
